### ISSUE TITLE
run demo.py

### ISSUE THREAD

**Issue by ketsu-shan** [HongwenZhang/PyMAF#20]
Traceback (most recent call last):
  File "demo.py", line 572, in <module>
    run_video_demo(args)
  File "demo.py", line 395, in run_video_demo
    renderer = PyRenderer(resolution=(orig_width, orig_height))
  File "/root/guoshsh/PyMAF-master/utils/renderer.py", line 65, in __init__
    point_size=1.0
  File "/root/softwares/anaconda3/envs/pymaf/lib/python3.6/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/root/softwares/anaconda3/envs/pymaf/lib/python3.6/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/root/softwares/anaconda3/envs/pymaf/lib/python3.6/site-packages/pyrender/platforms/egl.py", line 188, in init_context
    EGL_NO_CONTEXT, context_attributes
  File "/root/softwares/anaconda3/envs/pymaf/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 12297,
        baseOperation = eglCreateContext,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x7f4f4ffb2048>,
                <OpenGL._opaque.EGLConfig_pointer object at 0x7f4f4ffb2e18>,
                <OpenGL._opaque.EGLContext_pointer object at 0x7f4f36ac1400>,
                <OpenGL.arrays.lists.c_int_Array_7 object at 0x7f4f36aba6a8>,
        ),
        result = <OpenGL._opaque.EGLContext_pointer object at 0x7f4f50097400>
)

Hi,when I run the demo.py I got this problem with the code,I don"t know how to fix it out

**Comment by HongwenZhang** [comment]
Hi, it seems the pyopengl does not work correctly in your environment. The following issues may help. 
https://github.com/mmatl/pyrender/issues/86#issuecomment-767613647
https://github.com/mkocabas/VIBE/pull/2#issuecomment-793195239

You can also try using the OpenDR renderer for the demo by using `--use_opendr`.

**Comment by littlejiumi** [comment]
Add this:
MESA_GL_VERSION_OVERRIDE=4.1

**Comment by semchan** [comment]
> Add this: MESA_GL_VERSION_OVERRIDE=4.1

but still not working

**Comment by littlejiumi** [comment]
> > Add this: MESA_GL_VERSION_OVERRIDE=4.1
> 
> but still not working

Would you print your error?

**Comment by semchan** [comment]
> 

https://github.com/HongwenZhang/PyMAF/issues/20#issuecomment-998664394

**Comment by semchan** [comment]
> > > Add this: MESA_GL_VERSION_OVERRIDE=4.1
> > 
> > 
> > but still not working
> 
> Would you print your error?

File "demo.py", line 97, in run_image_demo
renderer = PyRenderer(resolution=(constants.IMG_RES, constants.IMG_RES))
File "/home/chenys/matting/PyMAF/utils/renderer.py", line 65, in init
point_size=1.0
File "/usr/local/lib/python3.7/site-packages/pyrender-0.1.45-py3.7.egg/pyrender/offscreen.py", line 31, in init
self._create()
File "/usr/local/lib/python3.7/site-packages/pyrender-0.1.45-py3.7.egg/pyrender/offscreen.py", line 149, in _create
self._platform.init_context()
File "/usr/local/lib/python3.7/site-packages/pyrender-0.1.45-py3.7.egg/pyrender/platforms/egl.py", line 177, in init_context
assert eglInitialize(self._egl_display, major, minor)
File "/usr/local/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 402, in call
return self( *args, **named )
File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
err = 12289,
baseOperation = eglInitialize,
cArguments = (
<OpenGL._opaque.EGLDisplay_pointer object at 0x7f698b96e0d0>,
c_long(0),
c_long(0),
),
result = 0

**Comment by Sunwenxin1** [comment]
> > > Add this: MESA_GL_VERSION_OVERRIDE=4.1
> > 
> > 
> > but still not working
> 
> Would you print your error?



> > > Add this: MESA_GL_VERSION_OVERRIDE=4.1
> > 
> > 
> > but still not working
> 
> Would you print your error?

@littlejiumi 师兄，我用了这个也不行，请问下您当时是怎样解决这个问题的呢
