### ISSUE TITLE
does anyone run the demo successfully in pytorch1.7.0 or higher version？

### ISSUE THREAD

**Issue by ShamLich** [HongwenZhang/PyMAF#29]
win11 rtx3080

when i try the demo,i got that error 

_Traceback (most recent call last):
  File "demo.py", line 39, in <module>
    from utils.renderer import OpenDRenderer, PyRenderer
  File "E:\Users\ShamLich\Documents\GitHub\PyMAF\utils\renderer.py", line 30, in <module>
    class WeakPerspectiveCamera(pyrender.Camera):
NameError: name 'pyrender' is not defined_

but i have already install the pyrender ,and if i change the code in  file 'renderer.py' from 

_try:
    import math
    import pyrender
    from pyrender.constants import RenderFlags
except:
    pass_

to

_import pyrender
try:
    import math
    from pyrender.constants import RenderFlags
except:
    pass_

i got this error,i dont know what is going on .

_Traceback (most recent call last):
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\site-packages\OpenGL\platform\egl.py", line 70, in EGL
    mode=ctypes.RTLD_GLOBAL
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\site-packages\OpenGL\platform\ctypesloader.py", line 45, in loadLibrary
    return dllType( name, mode )
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 39, in <module>
    from utils.renderer import OpenDRenderer, PyRenderer
  File "E:\Users\ShamLich\Documents\GitHub\PyMAF\utils\renderer.py", line 12, in <module>
    import pyrender
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\site-packages\pyrender\__init__.py", line 3, in <module>
    from .light import Light, PointLight, DirectionalLight, SpotLight
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\site-packages\pyrender\light.py", line 10, in <module>
    from OpenGL.GL import *
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\site-packages\OpenGL\GL\__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\site-packages\OpenGL\error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\site-packages\OpenGL\platform\__init__.py", line 35, in <module>
    _load()
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\site-packages\OpenGL\platform\__init__.py", line 32, in _load
    plugin.install(globals())
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\site-packages\OpenGL\platform\baseplatform.py", line 92, in install
    namespace[ name ] = getattr(self,name,None)
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\site-packages\OpenGL\platform\egl.py", line 93, in GetCurrentContext
    return self.EGL.eglGetCurrentContext
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\site-packages\OpenGL\platform\egl.py", line 73, in EGL
    raise ImportError("Unable to load EGL library", *err.args)
ImportError: ('Unable to load EGL library', 22, '找不到指定的模块。', None, 126, None, 'EGL', None)
(pymaf) PS E:\Users\ShamLich\Documents\GitHub\PyMAF> python utils/r.py
(pymaf) PS E:\Users\ShamLich\Documents\GitHub\PyMAF>  python utils/r.py
Traceback (most recent call last):
  File "utils/r.py", line 45, in <module>
    class PyRenderer:
  File "utils/r.py", line 83, in PyRenderer
    def __call__(self, verts, img=np.zeros((224, 224, 3)), cam=np.array([1, 0, 0]),
NameError: name 'np' is not defined
(pymaf) PS E:\Users\ShamLich\Documents\GitHub\PyMAF>  python utils/r.py
Traceback (most recent call last):
  File "utils/r.py", line 10, in <module>
    from models.smpl import get_smpl_faces
ModuleNotFoundError: No module named 'models'
(pymaf) PS E:\Users\ShamLich\Documents\GitHub\PyMAF>  python utils/r.py
(pymaf) PS E:\Users\ShamLich\Documents\GitHub\PyMAF> python demo.py --checkpoint=data/pretrained_model/PyMAF_model_checkpoint.pt --img_file examples/COCO_val2014_000000019667.jpg
Traceback (most recent call last):
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\site-packages\OpenGL\platform\egl.py", line 70, in EGL
    mode=ctypes.RTLD_GLOBAL
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\site-packages\OpenGL\platform\ctypesloader.py", line 45, in loadLibrary
    return dllType( name, mode )
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 39, in <module>
    from utils.renderer import OpenDRenderer, PyRenderer
  File "E:\Users\ShamLich\Documents\GitHub\PyMAF\utils\renderer.py", line 12, in <module>
    import pyrender
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\site-packages\pyrender\__init__.py", line 3, in <module>
    from .light import Light, PointLight, DirectionalLight, SpotLight
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\site-packages\pyrender\light.py", line 10, in <module>
    from OpenGL.GL import *
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\site-packages\OpenGL\GL\__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\site-packages\OpenGL\error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\site-packages\OpenGL\platform\__init__.py", line 35, in <module>
    _load()
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\site-packages\OpenGL\platform\__init__.py", line 32, in _load
    plugin.install(globals())
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\site-packages\OpenGL\platform\baseplatform.py", line 92, in install
    namespace[ name ] = getattr(self,name,None)
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\site-packages\OpenGL\platform\egl.py", line 93, in GetCurrentContext
    return self.EGL.eglGetCurrentContext
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "D:\Users\ShamLich\anaconda3\envs\pymaf\lib\site-packages\OpenGL\platform\egl.py", line 73, in EGL
    raise ImportError("Unable to load EGL library", *err.args)
ImportError: ('Unable to load EGL library', 22, '找不到指定的模块。', None, 126, None, 'EGL', None)_

**Comment by HongwenZhang** [comment]
Hi, I have not tried running the demo on Windows, but I have run the demo successfully on Ubuntu with pytorch1.8.1.
As the demo code is adapted from VIBE, it is recommended to have a look at the `windows-installation-tutorial` provided in VIBE (https://github.com/mkocabas/VIBE#windows-installation-tutorial).
