### ISSUE TITLE
fail to import Renderer. How to solve this problem?

### ISSUE THREAD

**Issue by a139122679** [HongwenZhang/PyMAF#34]
fail to import Renderer.
INFO:utils.train_utils:log name: logs/pymaf_res50_mix/pymaf_res50_mix_as_lp3_mlp256-128-64-5_Dec28-10-52-18-ZWK
INFO:models.hmr:loaded resnet50 imagenet pretrained model
INFO:datasets.base_dataset:len of h36m: 312188
INFO:datasets.base_dataset:len of lsp-orig: 1000
INFO:datasets.base_dataset:len of mpii: 14810
INFO:datasets.base_dataset:len of lspet: 9428
INFO:datasets.base_dataset:len of coco: 28344
INFO:datasets.base_dataset:len of mpi-inf-3dhp: 96507
INFO:datasets.base_dataset:len of h36m-p2-mosh: 26859
No renderer for visualization.
Traceback (most recent call last):
  File "train.py", line 69, in <module>
    main(None, ngpus_per_node, options)
  File "train.py", line 37, in main
    trainer = Trainer(options)
  File "/user3/lwx1055260/ID2462_PyMAF_for_pytorch/core/base_trainer.py", line 28, in __init__
    self.init_fn()
  File "/user3/lwx1055260/ID2462_PyMAF_for_pytorch/core/trainer.py", line 143, in init_fn
    self.iuv_maker = IUV_Renderer(output_size=cfg.MODEL.PyMAF.DP_HEATMAP_SIZE)
NameError: name 'IUV_Renderer' is not defined

**Comment by HongwenZhang** [comment]
`IUV_Renderer` is currently depended on [neural_renderer](https://github.com/daniilidis-group/neural_renderer).
If you fail to install [neural_renderer](https://github.com/daniilidis-group/neural_renderer), you can disable densepose rendering by setting `--misc MODEL.PyMAF.AUX_SUPV_ON False`.

**Comment by a139122679** [comment]
Thank you for your reply. After the neural_renderer dependency is installed, A new problem has arisen.. The Pyrender dependency is installed successfully. I do not know why the error message "pyrender undefined" is reported. Please check it.                                             Traceback (most recent call last):
  File "train.py", line 9, in <module>
    from core.trainer import Trainer
  File "/user3/lwx1055260/ID2462_PyMAF_for_pytorch/core/trainer.py", line 28, in <module>
    from utils.renderer import OpenDRenderer, IUV_Renderer
  File "/user3/lwx1055260/ID2462_PyMAF_for_pytorch/utils/renderer.py", line 30, in <module>
    class WeakPerspectiveCamera(pyrender.Camera):
NameError: name 'pyrender' is not defined

**Comment by HongwenZhang** [comment]
It seems that the `pyrender` package is not successfully imported or installed.

**Comment by a139122679** [comment]
It seems so, I removed the try method from your code, and now it's an error like this.                                                                                Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/PyOpenGL-3.1.0-py3.6.egg/OpenGL/platform/glx.py", line 17, in GL
    mode=ctypes.RTLD_GLOBAL
  File "/opt/conda/lib/python3.6/site-packages/PyOpenGL-3.1.0-py3.6.egg/OpenGL/platform/ctypesloader.py", line 45, in loadLibrary
    return dllType( name, mode )
  File "/opt/conda/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ('GL: cannot open shared object file: No such file or directory', 'GL', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 9, in <module>
    from core.trainer import Trainer
  File "/user3/lwx1055260/ID2462_PyMAF_for_pytorch/core/trainer.py", line 28, in <module>
    from utils.renderer import OpenDRenderer, IUV_Renderer
  File "/user3/lwx1055260/ID2462_PyMAF_for_pytorch/utils/renderer.py", line 21, in <module>
    import pyrender
  File "/opt/conda/lib/python3.6/site-packages/pyrender/__init__.py", line 3, in <module>
    from .light import Light, PointLight, DirectionalLight, SpotLight
  File "/opt/conda/lib/python3.6/site-packages/pyrender/light.py", line 10, in <module>
    from OpenGL.GL import *
  File "/opt/conda/lib/python3.6/site-packages/PyOpenGL-3.1.0-py3.6.egg/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/opt/conda/lib/python3.6/site-packages/PyOpenGL-3.1.0-py3.6.egg/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/opt/conda/lib/python3.6/site-packages/PyOpenGL-3.1.0-py3.6.egg/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/opt/conda/lib/python3.6/site-packages/PyOpenGL-3.1.0-py3.6.egg/OpenGL/platform/__init__.py", line 32, in _load
    plugin.install(globals())
  File "/opt/conda/lib/python3.6/site-packages/PyOpenGL-3.1.0-py3.6.egg/OpenGL/platform/baseplatform.py", line 92, in install
    namespace[ name ] = getattr(self,name,None)
  File "/opt/conda/lib/python3.6/site-packages/PyOpenGL-3.1.0-py3.6.egg/OpenGL/platform/baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "/opt/conda/lib/python3.6/site-packages/PyOpenGL-3.1.0-py3.6.egg/OpenGL/platform/glx.py", line 96, in GetCurrentContext
    return self.GL.glXGetCurrentContext
  File "/opt/conda/lib/python3.6/site-packages/PyOpenGL-3.1.0-py3.6.egg/OpenGL/platform/baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "/opt/conda/lib/python3.6/site-packages/PyOpenGL-3.1.0-py3.6.egg/OpenGL/platform/glx.py", line 20, in GL
    raise ImportError("Unable to load OpenGL library", *err.args)
ImportError: ('Unable to load OpenGL library', 'GL: cannot open shared object file: No such file or directory', 'GL', None)

**Comment by HongwenZhang** [comment]
We have only tested our code on Ubuntu. I have no idea about the above errors :(
You can also refer to the answers in Issue #20.
