### ISSUE TITLE
error while render/visualize

### ISSUE THREAD

**Issue by agnJason** [HongwenZhang/PyMAF#45]
First error occured while training:
Traceback (most recent call last):r15-19-58-15-iXP Epoch 0:  41%|████      | 1000/2438 [31:24<29:48,  1.24s/it] 
  File "train.py", line 69, in <module>
    main(None, ngpus_per_node, options)
  File "train.py", line 38, in main
    trainer.fit()
  File "/home/gqj/PyMAF/core/trainer.py", line 502, in fit
    self.train(epoch)
  File "/home/gqj/PyMAF/core/trainer.py", line 294, in train
    self.visualize(self.step_count, batch, 'train', **out)
  File "/home/gqj/miniconda3/envs/gqj/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/gqj/PyMAF/core/trainer.py", line 676, in visualize
    render_imgs.append(self.renderer(
TypeError: __call__() got an unexpected keyword argument 'image'
fixed it by modify trainer.py:
```python
                    image=img_vis,  #704
```

next trouble:
Traceback (most recent call last):_Apr15-21-13-13-jDp Epoch 0:  41%|████      | 1000/2438 [13:46<17:42,  1.35it/s] 
  File "train.py", line 69, in <module>
    main(None, ngpus_per_node, options)
  File "train.py", line 38, in main
    trainer.fit()
  File "/home/gqj/PyMAF/core/trainer.py", line 502, in fit
    self.train(epoch)
  File "/home/gqj/PyMAF/core/trainer.py", line 294, in train
    self.visualize(self.step_count, batch, 'train', **out)
  File "/home/gqj/miniconda3/envs/gqj/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/gqj/PyMAF/core/trainer.py", line 676, in visualize
    render_imgs.append(self.renderer(
  File "/home/gqj/PyMAF/utils/renderer.py", line 211, in __call__
    if faces == None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
fixed it by modify renderer.py:
```python
        try:                       # line 211
            faces.shape
        except:
            faces = self.faces
```

Another problem I cannot solved:
Traceback (most recent call last):
  File "train.py", line 69, in <module>
    main(None, ngpus_per_node, options)
  File "train.py", line 38, in main
    trainer.fit()
  File "/home/gqj/PyMAF/core/trainer.py", line 502, in fit
    self.train(epoch)
  File "/home/gqj/PyMAF/core/trainer.py", line 294, in train
    self.visualize(self.step_count, batch, 'train', **out)
  File "/home/gqj/miniconda3/envs/gqj/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/gqj/PyMAF/core/trainer.py", line 676, in visualize
    render_imgs.append(self.renderer(
  File "/home/gqj/PyMAF/utils/renderer.py", line 276, in __call__
    rendered_image = rn.r
  File "/home/gqj/miniconda3/envs/gqj/lib/python3.8/site-packages/chumpy/ch.py", line 594, in r
    self._call_on_changed()
  File "/home/gqj/miniconda3/envs/gqj/lib/python3.8/site-packages/chumpy/ch.py", line 589, in _call_on_changed
    self.on_changed(self._dirty_vars)
  File "/home/gqj/miniconda3/envs/gqj/lib/python3.8/site-packages/opendr-0.73-py3.8.egg/opendr/renderer.py", line 1082, in on_changed
    self.vbo_verts_face.set_array(np.array(self.verts_by_face).astype(np.float32))
AttributeError: 'ColoredRenderer' object has no attribute 'vbo_verts_face'
pymaf_res50_as_lp3_mlp256-128-64-5_Apr15-21-31-20-AfG Epoch 0:  41%|████      | 1000/2438 [11:21<16:20,  1.47it/s]

Could you please check out this bug?

**Comment by agnJason** [comment]
I solved it by reinstall opendr
