### ISSUE TITLE
Questions about training in remote server

### ISSUE THREAD

**Issue by Italy2006** [HongwenZhang/PyMAF#50]
Traceback (most recent call last):
  File "train.py", line 69, in <module>
    main(None, ngpus_per_node, options)
  File "train.py", line 37, in main
    trainer = Trainer(options)
  File "/root/ours/pymaf/core/base_trainer.py", line 28, in __init__
    self.init_fn()
  File "/root/ours/pymaf/core/trainer.py", line 56, in init_fn
    self.smpl_render =  PyRenderer(resolution=(constants.IMG_RES, constants.IMG_RES))
  File "/root/ours/pymaf/utils/renderer.py", line 446, in __init__
    point_size=1.0
  File "/opt/conda/envs/mono/lib/python3.6/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/opt/conda/envs/mono/lib/python3.6/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/opt/conda/envs/mono/lib/python3.6/site-packages/pyrender/platforms/pyglet_platform.py", line 52, in init_context
    width=1, height=1)
  File "/opt/conda/envs/mono/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 165, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/opt/conda/envs/mono/lib/python3.6/site-packages/pyglet/window/__init__.py", line 570, in __init__
    display = pyglet.canvas.get_display()
  File "/opt/conda/envs/mono/lib/python3.6/site-packages/pyglet/canvas/__init__.py", line 94, in get_display
    return Display()
  File "/opt/conda/envs/mono/lib/python3.6/site-packages/pyglet/canvas/xlib.py", line 123, in __init__
    raise NoSuchDisplayException('Cannot connect to "%s"' % name)
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"

Have you ever encountered this problem? I don't have these problems when I train locally but when I train on the server it does

**Comment by lai-pf** [comment]
您好 我也在了解这篇论文 请问您方便分享一下 final_fits/h36m.npy and static_fits/h36m.npy两个文件给我吗 
我的邮箱是dr.henrylai@gmail.com

**Comment by HongwenZhang** [comment]
Have you tried using `os.environ['PYOPENGL_PLATFORM'] = 'egl'`?
