### ISSUE TITLE
Index out of range and Cant set Attribute errors close to end of execution.

### ISSUE THREAD

**Issue by jdavies** [HongwenZhang/PyMAF#67]
I got past the J_Regressor issue (thanks to earlier folks that raised that issues and got answers). I'm getting a different error now,  I believe it is close to the end of the execution path. Here is my stack trace:

`[(0) "the person walked forward and is picking up his toolbox." | Rep #0 | -> sample00_rep00.mp4]
MovieWriter ffmpeg unavailable; using Pillow instead.
Traceback (most recent call last):
  File "C:\Users\jeff\anaconda3\envs\mdm\lib\site-packages\matplotlib\animation.py", line 234, in saving
    yield self
  File "C:\Users\jeff\anaconda3\envs\mdm\lib\site-packages\matplotlib\animation.py", line 1076, in save
    anim._init_draw()  # Clear the initial frame
  File "C:\Users\jeff\anaconda3\envs\mdm\lib\site-packages\matplotlib\animation.py", line 1696, in _init_draw
    self._draw_frame(frame_data)
  File "C:\Users\jeff\anaconda3\envs\mdm\lib\site-packages\matplotlib\animation.py", line 1718, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
  File "D:\GitHub\motion-diffusion-model\data_loaders\humanml\utils\plot_script.py", line 89, in update
    ax.lines = []
AttributeError: can't set attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jeff\anaconda3\envs\mdm\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\jeff\anaconda3\envs\mdm\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\GitHub\motion-diffusion-model\sample.py", line 175, in <module>
    main()
  File "D:\GitHub\motion-diffusion-model\sample.py", line 167, in main
    plot_3d_motion(animation_save_path, skeleton, motion, title=caption, fps=fps)
  File "D:\GitHub\motion-diffusion-model\data_loaders\humanml\utils\plot_script.py", line 122, in plot_3d_motion
    ani.save(save_path, fps=fps)
  File "C:\Users\jeff\anaconda3\envs\mdm\lib\site-packages\matplotlib\animation.py", line 1093, in save
    writer.grab_frame(**savefig_kwargs)
  File "C:\Users\jeff\anaconda3\envs\mdm\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\jeff\anaconda3\envs\mdm\lib\site-packages\matplotlib\animation.py", line 236, in saving
    self.finish()
  File "C:\Users\jeff\anaconda3\envs\mdm\lib\site-packages\matplotlib\animation.py", line 512, in finish
    self._frames[0].save(
IndexError: list index out of range`

Any idea's what might be wrong? TIA!

**Comment by jdavies** [comment]
Oh, and this is on a Windows 10 box using Anaconda 2021_05 (version 4.10.1)  with  Python 3.7.12

**Comment by HongwenZhang** [comment]
Hi @jdavies, should it be an issue reported in motion-diffusion-model? not PyMAF?
